In [1]:
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

import pymysql
pymysql.install_as_MySQLdb()

from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.orm import Session

In [3]:
yahoo_df = pd.read_csv("yahoo.csv")
iex_df = pd.read_csv("iex.csv")
yahoo_df

,Date,Open,High,Low,Close,Volume,Symbol,Source,Event
0,2018-05-15,46.51,46.99,46.27,46.79,"7,149,600",BP,Yahoo!,Coordination
1,2018-05-15,249.48,249.58,246.25,247.34,"1,638,200",FDX,Yahoo!,Coordination
2,2018-05-15,54.58,54.75,53.56,53.92,"21,712,600",INTC,Yahoo!,Coordination
3,2018-05-15,97.24,97.85,96.34,97.32,"24,594,000",MSFT,Yahoo!,Coordination
4,2018-05-15,46.51,46.82,46.25,46.81,"11,304,900",ORCL,Yahoo!,Coordination
5,2018-05-15,115.78,116.47,114.85,115.61,"3,480,400",UPS,Yahoo!,Coordination
6,2018-05-15,81.85,82.03,81.40,81.79,"12,595,700",XOM,Yahoo!,Coordination
7,2018-05-16,46.80,46.82,46.43,46.71,"4,866,500",BP,Yahoo!,Coordination
8,2018-05-16,247.78,248.72,246.54,247.12,"1,101,200",FDX,Yahoo!,Coordination
9,2018-05-16,54.17,54.70,53.96,54.64,"16,260,500",INTC,Yahoo!,Coordination
10,2018-05-16,97.36,97.40,96.62,97.15,"17,384,700",MSFT,Yahoo!,Coordination
11,2018-05-16,46.93,46.93,46.45,46.73,"9,874,200",ORCL,Yahoo!,Coordination
12,2018-05-16,115.54,116.67,115.53,116.32,"1,970,000",UPS,Yahoo!,Coordination
13,2018-05-16,81.76,82.05,81.17,82.02,"9,570,000",XOM,Yahoo!,Coordination
14,2018-05-17,47.01,47.37,46.93,47.19,"7,207,900",BP,Yahoo!,Coordination
15,2018-05-17,247.69,250.23,247.28,248.46,"1,084,000",FDX,Yahoo!,Coordination
16,2018-05-17,54.55,55.44,54.42,54.81,"16,872,600",INTC,Yahoo!,Coordination
17,2018-05-17,96.76,97.54,95.83,96.18,"17,246,700",MSFT,Yahoo!,Coordination
18,2018-05-17,46.69,47.06,46.42,46.54,"10,162,300",ORCL,Yahoo!,Coordination
19,2018-05-17,116.59,117.44,116.40,116.59,"3,697,200",UPS,Yahoo!,Coordination
20,2018-05-17,82.20,82.28,81.44,81.88,"11,224,100",XOM,Yahoo!,Coordination
21,2018-05-18,47.30,47.44,47.14,47.38,"4,276,600",BP,Yahoo!,Coordination
22,2018-05-18,247.88,249.73,246.71,249.45,"1,195,700",FDX,Yahoo!,Coordination
23,2018-05-18,54.53,54.54,53.47,53.50,"23,679,900",INTC,Yahoo!,Coordination
24,2018-05-18,96.01,96.93,96.01,96.36,"17,865,800",MSFT,Yahoo!,Coordination
25,2018-05-18,46.69,46.79,46.24,46.32,"13,517,300",ORCL,Yahoo!,Coordination
26,2018-05-18,115.67,115.93,115.10,115.38,"2,450,900",UPS,Yahoo!,Coordination
27,2018-05-18,81.55,81.80,81.26,81.30,"10,030,900",XOM,Yahoo!,Coordination
28,2018-05-21,47.38,47.83,47.38,47.79,"5,412,100",BP,Yahoo!,Coordination
29,2018-05-21,251.00,254.94,250.68,254.66,"1,384,200",FDX,Yahoo!,Coordination
...,...,...,...,...,...,...,...,...,...
180,2018-06-20,114.75,114.78,113.53,113.65,"3,112,600",UPS,Yahoo!,Aftermath
181,2018-06-20,80.85,81.13,80.27,80.45,"8,917,700",XOM,Yahoo!,Aftermath
182,2018-06-21,44.61,44.63,44.12,44.16,"5,016,700",BP,Yahoo!,Aftermath
183,2018-06-21,251.51,251.80,245.65,246.72,"3,665,100",FDX,Yahoo!,Aftermath
184,2018-06-21,54.38,54.53,51.94,52.19,"44,435,600",INTC,Yahoo!,Aftermath
185,2018-06-21,102.08,102.46,100.88,101.14,"23,198,200",MSFT,Yahoo!,Aftermath
186,2018-06-21,43.18,43.84,42.98,43.10,"32,635,100",ORCL,Yahoo!,Aftermath
187,2018-06-21,113.66,114.07,112.32,113.42,"2,721,900",UPS,Yahoo!,Aftermath
188,2018-06-21,80.02,80.38,79.33,79.69,"10,990,700",XOM,Yahoo!,Aftermath
189,2018-06-22,45.82,46.17,45.70,45.78,"8,878,700",BP,Yahoo!,Aftermath
190,2018-06-22,247.90,248.14,241.50,241.77,"2,635,600",FDX,Yahoo!,Aftermath
191,2018-06-22,52.62,53.09,52.30,52.50,"34,682,100",INTC,Yahoo!,Aftermath
192,2018-06-22,100.41,100.77,99.63,100.41,"38,923,100",MSFT,Yahoo!,Aftermath
193,2018-06-22,43.20,44.30,43.16,44.10,"29,735,100",ORCL,Yahoo!,Aftermath
194,2018-06-22,114.90,115.79,113.63,113.70,"3,536,300",UPS,Yahoo!,Aftermath
195,2018-06-22,81.16,81.94,80.92,81.38,"16,012,200",XOM,Yahoo!,Aftermath
196,2018-06-25,44.92,44.99,44.05,44.24,"6,257,800",BP,Yahoo!,Aftermath
197,2018-06-25,239.73,240.33,231.98,234.53,"3,605,700",FDX,Yahoo!,Aftermath
198,2018-06-25,51.17,51.75,49.91,50.71,"45,356,500",INTC,Yahoo!,Aftermath
199,2018-06-25,100.00,100.11,97.30,98.39,"35,433,300",MSFT,Yahoo!,Aftermath
200,2018-06-25,43.57,44.47,43.49,44.28,"24,640,500",ORCL,Yahoo!,Aftermath
201,2018-06-25,113.04,113.04,109.39,110.20,"4,044,300",UPS,Yahoo!,Aftermath
202,2018-06-25,80.78,81.24,79.30,79.74,"10,557,200",XOM,Yahoo!,Aftermath
203,2018-06-26,44.98,45.10,44.51,44.89,"8,334,200",BP,Yahoo!,Aftermath
204,2018-06-26,235.60,237.93,233.70,236.85,"1,954,200",FDX,Yahoo!,Aftermath
205,2018-06-26,49.95,50.41,49.36,49.67,"37,543,000",INTC,Yahoo!,Aftermath
206,2018-06-26,98.82,100.08,98.75,99.08,"26,897,200",MSFT,Yahoo!,Aftermath
207,2018-06-26,44.46,44.85,44.37,44.41,"20,717,500",ORCL,Yahoo!,Aftermath
208,2018-06-26,110.39,110.70,109.20,109.57,"2,332,300",UPS,Yahoo!,Aftermath
209,2018-06-26,80.15,81.01,79.97,80.64,"10,382,800",XOM,Yahoo!,Aftermath

In [3]:
class stocks(Base):
    __tablename__="stock_data"
    id = Column(Integer, primary_key=True)
    Date = Column(String)
    Open = Column(Float)
    High = Column(Float)
    Low = Column(Float)
    Close = Column(Float)
    Adj_Close = Column(Float)
    Volume = Column(Integer)
    Symbol = Column(String)
    Event = Column(String)

In [4]:
hashtag_df = pd.read_csv("Hashtags_combined.csv")
hashtag_df

            Hashtag  Count        Event
0              DPRK   3866       Summit
1               ROK   1636       Summit
2             Japan   1548       Summit
3    TrumpKimSummit    734       Summit
4   SingaporeSummit    690       Summit
5             China    360       Summit
6             Trump    330       Summit
7        NorthKorea    330       Summit
8              DPRK  19045  Rescheduled
9        NorthKorea   2794  Rescheduled
10         BREAKING   1130  Rescheduled
11            Trump    993  Rescheduled
12     AmericaFirst    515  Rescheduled
13    QuoteOfTheDay    475  Rescheduled
14           Lavrov    467  Rescheduled
15               US    397  Rescheduled

In [5]:
class hashtag(Base):
    __tablename__="hashtags"
    id = Column(Integer, primary_key=True)
    hashtag = Column(String)
    count = Column(Integer)
    event = Column(String)

In [6]:
engine = create_engine('sqlite:///stocks_hashtags_V1.sqlite', echo=False)
Base.metadata.create_all(engine)
session = Session(engine)

In [7]:
for index, row in stock_df.iterrows():
    print(row['Symbol'])
    session.add(stocks(Date = row['Date'], Open = row['Open'], High = row['High'], Low = row['Low'], Close = row['Close'], Adj_Close = row['Adj_Close'], Volume = row['Volume'], Symbol = row['Symbol'], Event = row['Event']))

for index, row in hashtag_df.iterrows():
    print(row['Hashtag'])
    session.add(hashtag(hashtag = row['Hashtag'], count = row['Count'], event = row['Event']))

GSPC
GSPC
GSPC
GSPC
GSPC
GSPC
GSPC
GSPC
GSPC
GSPC
EUXL
EUXL
EUXL
EUXL
EUXL
EUXL
EUXL
EUXL
EUXL
EUXL
DJA
DJA
DJA
DJA
DJA
DJA
DJA
DJA
DJA
DJA
DPRK
ROK
Japan
TrumpKimSummit
SingaporeSummit
China
Trump
NorthKorea
DPRK
NorthKorea
BREAKING
Trump
AmericaFirst
QuoteOfTheDay
Lavrov
US

In [8]:
session.commit()